## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ecmp-drb',
                                 ['point-to-point', 'applications', 'internet', 'xpath-routing', 'tlb', 'tlb-probing', 'flow-monitor', 'drb-routing'])
    obj.source = ['experiment.cc']

